In [2]:
# !pip install owlready2

In [3]:
import pandas as pd
import numpy as np

In [4]:
from owlready2 import *
onto_path.append("/path/to/your/local/ontology/repository")
onto = get_ontology("https://files.ifi.uzh.ch/ddis/oldweb/ddis/fileadmin/ont/nli/geography.owl")
onto.load()

* Owlready2 * Warning: optimized Cython parser module 'owlready2_optimized' is not available, defaulting to slower Python implementation

get_ontology("http://www.mooney.net/geo#")

In [5]:
data = {'name': [],
        'area': [],
        'population': [],
        'pop_density': [],
        'lowest_elevation': [],
        'highest_elevation': []}

df_states = pd.DataFrame(data)

states_data = onto.search(type = onto.State)
low_elevation_data = onto.search(type = onto.LoPoint)
high_elevation_data = onto.search(type = onto.HiPoint)

for state in states_data:
    statename = state.name
    for prop in state.get_properties():
        for value in prop[state]:
            if prop.python_name == "statePopulation":
                statearea = int(value)
            elif prop.python_name == "stateArea":
                statepop = int(value)
            
            for low_elevation in  low_elevation_data:
                if(low_elevation.isLowestPointOf[0].name == statename):
                    stateloel = int(low_elevation.loElevation[0])
            
            for high_elevation in  high_elevation_data:
                if(high_elevation.isHighestPointOf[0].name == statename):
                    statehiel = int(high_elevation.hiElevation[0])
    
    statepopdense = statepop / statearea
    state_data = {'name': statename, 'area': statearea, 'population': statepop, 'pop_density': statepopdense, 'lowest_elevation': stateloel, 'highest_elevation': statehiel}
    df_states = df_states.append(state_data, ignore_index=True)

df_states = df_states.sort_values('pop_density')

display(df_states)

,name,area,population,pop_density,lowest_elevation,highest_elevation
5,alaska,591000.0,401800.0,0.679865,0.0,6194.0
20,wyoming,97809.0,469557.0,4.800755,945.0,4202.0
35,montana,147000.0,786700.0,5.351701,549.0,3901.0
11,nevada,110500.0,800500.0,7.244344,143.0,4005.0
45,southDakota,77116.0,690767.0,8.957506,284.0,2207.0
50,northDakota,70700.0,652700.0,9.231966,229.0,1069.0
9,newMexico,121600.0,1303000.0,10.715461,859.0,4011.0
34,idaho,83000.0,944000.0,11.373494,216.0,3859.0
7,utah,84900.0,1461000.0,17.208481,610.0,4123.0
18,nebraska,77300.0,1569000.0,20.297542,256.0,1654.0
6,arizona,114000.0,2718000.0,23.842105,21.0,3851.0
17,oregon,97073.0,2633000.0,27.123917,0.0,3424.0
8,colorado,104000.0,2889000.0,27.778846,1021.0,4399.0
19,kansas,82300.0,2364000.0,28.724180,207.0,1231.0
40,kentucky,82300.0,2364000.0,28.724180,78.0,1263.0
47,maine,33265.0,1125000.0,33.819330,0.0,1606.0
12,arkansas,53200.0,2286000.0,42.969925,17.0,839.0
16,oklahoma,69950.0,3025000.0,43.245175,87.0,1516.0
44,minnesota,84400.0,4076000.0,48.293839,183.0,701.0
41,iowa,56300.0,2913000.0,51.740675,146.0,511.0
4,mississippi,47700.0,2520000.0,52.830189,0.0,246.0
49,vermont,9614.0,511500.0,53.203661,29.0,1339.0
15,texas,266807.0,14229000.0,53.330685,0.0,2667.0
36,washington,68139.0,4113200.0,60.364842,0.0,4392.0
13,missouri,69700.0,4916000.0,70.530846,70.0,540.0
0,alabama,51700.0,3894000.0,75.319149,0.0,734.0
46,westVirginia,24200.0,1950000.0,80.578512,73.0,1482.0
38,wisconsin,56153.0,4700000.0,83.699891,177.0,595.0
14,louisiana,47700.0,4206000.0,88.176101,-1.0,163.0
2,georgia,58900.0,5463000.0,92.750424,0.0,1458.0
48,newHampshire,9279.0,920600.0,99.213277,0.0,1917.0
32,southCarolina,31113.0,3121800.0,100.337480,0.0,1085.0
1,tennessee,42140.0,4591000.0,108.946369,55.0,2025.0
31,northCarolina,52670.0,5882000.0,111.676476,0.0,2037.0
30,virginia,40760.0,5346800.0,131.177625,0.0,1746.0
3,florida,68664.0,9746000.0,141.937551,0.0,105.0
33,hawaii,6471.0,964000.0,148.972338,0.0,4205.0
10,california,158000.0,23670000.0,149.810127,-85.0,4418.0
39,indiana,36200.0,5490000.0,151.657459,98.0,383.0
42,michigan,58500.0,9262000.0,158.324786,174.0,604.0
37,illinois,56300.0,11400000.0,202.486679,85.0,376.0
43,ohio,41300.0,10800000.0,261.501211,132.0,472.0
26,pennsylvania,45308.0,11863000.0,261.830140,0.0,979.0
25,delaware,2044.0,594000.0,290.606654,0.0,135.0
24,newYork,49100.0,17558000.0,357.596741,0.0,1629.0
28,maryland,10460.0,4217000.0,403.154876,0.0,1024.0
29,districtOfColumbia,1100.0,638000.0,580.000000,0.0,125.0
21,connecticut,5020.0,3107000.0,618.924303,0.0,725.0
22,massachusetts,8284.0,5737000.0,692.539836,0.0,1064.0
23,rhodeIsland,1212.0,947200.0,781.518152,0.0,247.0
27,newJersey,7787.0,7365000.0,945.807114,0.0,550.0

In [6]:
# boxplot = df_states.boxplot(column=['pop_density'])

In [7]:
stats = df_states.describe()

# print(stats)
pd_min = stats.loc['min', 'pop_density']
pd_med = stats.loc['50%', 'pop_density']
pd_max = stats.loc['max', 'pop_density']

print(pd_min)
print(pd_med)
print(pd_max)

le_min = stats.loc['min', 'lowest_elevation']
le_max = stats.loc['max', 'lowest_elevation']

print(le_min)
print(le_max)

he_min = stats.loc['min', 'highest_elevation']
he_max = stats.loc['max', 'highest_elevation']

print(he_min)
print(he_max)

0.6798646362098139
75.31914893617021
945.8071144214717
-85.0
1021.0
105.0
6194.0

In [8]:
data = {'name': [],
        'population': [],
        'state': [],
        'capital': []}

df_cities = pd.DataFrame(data)

cities_data = onto.search(type = onto.City)
capital_data = onto.search(type = onto.Capital)

for city in cities_data:
    cityname = city.name
    capital = False
    for prop in city.get_properties():
        for value in prop[city]:
            if prop.python_name == "cityPopulation":
                citypop = int(value)
            elif prop.python_name == "isCityOf":
                citystate = value.name
    
    city_data = {'name': cityname, 'population': citypop, 'state': citystate, 'capital': capital}
    df_cities = df_cities.append(city_data, ignore_index=True)

for city in capital_data:
    cityname = city.name
    capital = True
    for prop in city.get_properties():
        for value in prop[city]:
            if prop.python_name == "cityPopulation":
                citypop = int(value)
            elif prop.python_name == "isCityOf":
                citystate = value.name
    
    city_data = {'name': cityname, 'population': citypop, 'state': citystate, 'capital': capital}
    df_cities = df_cities.append(city_data, ignore_index=True)    

df_cities = df_cities.sort_values('population')

print(df_cities)

               name  population         state  capital
81   scottsValleyCa      6037.0    california      0.0
396    montpelierVt      7806.0       vermont      0.0
447    montpelierVt      7806.0       vermont      1.0
392        pierreSd     14032.0   southDakota      0.0
443        pierreSd     14032.0   southDakota      1.0
..              ...         ...           ...      ...
297       houstonTx   1595138.0         texas      0.0
274  philadelphiaPa   1688210.0  pennsylvania      0.0
12     losAngelesCa   2966850.0    california      0.0
121       chicagoIl   3005172.0      illinois      0.0
234       newYorkNy   7071639.0       newYork      0.0

[453 rows x 4 columns]

In [9]:
stats = df_cities.describe()

# print(stats)
pop_min = stats.loc['min', 'population']
pop_med = stats.loc['50%', 'population']
pop_max = stats.loc['max', 'population']

print(pop_min)
print(pop_med)
print(pop_max)

6037.0
91450.0
7071639.0

In [10]:
def rateState(city, stateDense):      
    doms = 0
    city_popdense = int(city.isCityOf[0].stateArea[0]) / int(city.isCityOf[0].statePopulation[0])
    if(stateDense == "Rural" or stateDense == "rural"):
        doms = (pd_med - city_popdense) / (pd_med - pd_min)
        
    elif(stateDense == "Suburban" or stateDense == "suburban"):
        if(city_popdense <= pd_med):
            doms = (city_popdense - pd_min) / (pd_med - pd_min)
        elif(city_popdense > pd_med):
            doms = (pd_max - city_popdense) / (pd_max - pd_med)
            
    elif(stateDense == "Urban" or stateDense == "urban"):
        doms = (city_popdense - pd_med) / (pd_max - pd_med)
    
    if(doms < 0):
        doms = 0
    
    return doms

In [11]:
def rateCity(city, cityPop):      
    domc = 0
    city_pop = int(city.cityPopulation[0])
    if(cityPop == "Small" or cityPop == "small"):
        domc = (pop_med - city_pop) / (pop_med - pop_min)
        
    elif(cityPop == "Medium" or cityPop == "medium"):
        if(city_pop <= pop_med):
            domc = (city_pop - pop_min) / (pop_med - pop_min)
        elif(city_pop > pop_med):
            domc = (pop_max - city_pop) / (pop_max - pop_med)
            
    elif(cityPop == "Large" or cityPop == "large"):
        domc = (city_pop - pop_med) / (pop_max - pop_med)
    
    if(domc < 0):
        domc = 0
    
    return domc

In [12]:
def rateElevation(city, elevation):
    doml = 0
    domh = 0
    dome = 0
    
    low_elevation_data = onto.search(is_a = onto.LoPoint, isLowestPointOf = city.isCityOf[0])
    high_elevation_data = onto.search(is_a = onto.HiPoint, isHighestPointOf = city.isCityOf[0])
    
    lo_elev = int(low_elevation_data[0].loElevation[0])
    hi_elev = int(high_elevation_data[0].hiElevation[0])

    if(elevation == "Low" or elevation == "low"):
        doml = (le_max - lo_elev) / (le_max - le_min)
        domh = (he_max - hi_elev) / (he_max - he_min)        
           
    elif(elevation == "High" or elevation == "high"):
        doml = (lo_elev - le_min) / (le_max - le_min)
        domh = (hi_elev - he_min) / (he_max - he_min)
    
    dome = (doml + domh)/2
    
    return dome

In [13]:
def recommendation_rating(result, stateDense, cityPop, elevation, importantFeat):
        
    values = [["stateDense", rateState(result, stateDense)], ["cityPop", rateCity(result, cityPop)], ["elevation", rateElevation(result, elevation)]]
    weights = [1/3, 1/3, 1/3]
    
    max_value = 0
    for j in range(len(values)):
        if(values[j][0] > values[max_value][0]):
            max_value = j
            
    if(values[max_value][1]<0.5):
        rec_desc = "-"
    elif(values[max_value][0]=="stateDense"):
        rec_desc = stateDense + " Population Density"
    elif(values[max_value][0]=="cityPop"):
        rec_desc = cityPop + " Population"
    elif(values[max_value][0]=="elevation"):
        rec_desc = elevation + " Elevation"         
    
    if(importantFeat == "Population" or importantFeat == "population"):
        weights[:] = [2/4, 1/4, 1/4]
        values.insert(0, values.pop(1))

    elif(importantFeat == "Density" or importantFeat == "density"):
        weights[:] = [2/4, 1/4, 1/4]
        values.insert(0, values.pop(0))
    elif(importantFeat == "Elevation" or importantFeat == "elevation"):
        weights[:] = [2/4, 1/4, 1/4]
        values.insert(0, values.pop(2))
    else:
        values = sorted(values, key=lambda l:l[1])
        
#     print(values)    
 
    rec_rate = 0
   
    for i in range(len(values)):
        rec_rate = rec_rate + (values[i][1] * weights[i])
    
    return rec_rate, rec_desc

In [54]:
def processInput(city, state, stateDense, cityPop, elevation, importantFeat):
    data = {'city': [],
            'population': [],
            'state': [],
            'state_density': [],
            'lowest_elevation': [], 
            'highest_elevation': [],
            'capital': [],
            'rec_rating': [],
            'description': []}

    df_rec = pd.DataFrame(data)

#     results = onto.search(is_a = onto.City, isCityOf = onto.search(iri=state, type = onto.State))
    city_results = onto.search(iri=city, type = onto.City)
    state_results = onto.search(iri=state, type = onto.State)
    
    results = []
    
    for city in city_results:
        for state in state_results:
            if(city.isCityOf[0]==state):
                results.append(city)
                break
            
#     print(results)
    
    for result in results:
        low_results = onto.search(type = onto.LoPoint, isLowestPointOf = result.isCityOf[0])
        high_results = onto.search(type = onto.HiPoint, isHighestPointOf = result.isCityOf[0])

        if(result.__class__.name == "Capital"):
            capital = True
        else:
            capital = False
        
        pop_dense = int(result.isCityOf[0].stateArea[0]) / int(result.isCityOf[0].statePopulation[0])
        
        lowest_el = low_results[0].loElevation[0]
        highest_el = high_results[0].hiElevation[0]
        
        rec_rating, rec_desc = recommendation_rating(result, stateDense, cityPop, elevation, importantFeat)
        
       
        result_data = {'city': result.name[:-2], 
                       'population': int(result.cityPopulation[0]), 
                       'state': result.isCityOf[0].name, 
                       'state_density': pop_dense,
                       'lowest_elevation': lowest_el, 
                       'highest_elevation': highest_el,
                       'capital': capital,
                       'rec_rating': rec_rating, 
                       'description': rec_desc}
        df_rec = df_rec.append(result_data, ignore_index=True)
        df_rec = df_rec.sort_values('rec_rating', ascending = False)
    
    return df_rec

In [70]:
def main():
    print("==== Ontology-Based Fuzzy Logic Recommender Systems ====")
    print()
    city = "*" + input("Masukkan city yang diinginkan\t\t\t\t: ") + "*"
    state =  "*" + input("Masukkan state yang diinginkan\t\t\t\t: ") + "*"
    stateDense = input("Populasi density (Urban, Suburban, Rural)\t\t: ")
    cityPop = input("Populasi (Small, Medium, Large)\t\t\t\t: ")
    elevation = input("Elevasi (Low, High)\t\t\t\t\t: ")
    importantFeat = input("Important Feature (Population, Density, Elevation)\t: ")
    print()
    print("========================================================")
    
    df = processInput(city, state, stateDense, cityPop, elevation, importantFeat)
    df.index += 1 
    with pd.option_context('display.max_columns', None,
                           'display.width', 1000,
                           'display.colheader_justify', 'center'):
#         display(df[:10])
        df = df[["city", "rec_rating"]]
        display(df[:5])

In [74]:
if __name__ == '__main__':
    main()

==== Ontology-Based Fuzzy Logic Recommender Systems ====

Masukkan city yang diinginkan				:
Masukkan state yang diinginkan				:
Populasi density (Urban, Suburban, Rural)		: urban
Populasi (Small, Medium, Large)				: medium
Elevasi (Low, High)					: high
Important Feature (Population, Density, Elevation)	:

========================================================

      city     rec_rating
1     trenton   0.691624
2   elizabeth   0.690952
3    paterson   0.689434
4  woodbridge   0.686286
5  jerseyCity   0.685349